# Generated by Django 4.0.1 on 2022-01-11 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='branch',
            fields=[
                ('branch_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('branch', models.CharField(default='default', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='class_courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='classroom',
            fields=[
                ('class_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=5)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_classroom_app.branch')),
            ],
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('course_name', models.CharField(max_length=150)),
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('is_elective', models.BooleanField(default=False)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_classroom_app.branch')),
            ],
        ),
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='sem',
            fields=[
                ('sem', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=1, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='to_do',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('due_date', models.DateField()),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_classroom_app.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='time_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20)),
                ('time', models.TimeField(choices=[('8:30 - 9:30', '8:30 - 9:30'), ('9:30 - 10:30', '9:30 - 10:30'), ('11:00 - 11:50', '11:00 - 11:50'), ('11:50 - 12:40', '11:50 - 12:40'), ('12:40 - 1:30', '12:40 - 1:30'), ('2:30 - 3:30', '2:30 - 3:30'), ('3:30 - 4:30', '3:30 - 4:30'), ('4:30 - 5:30', '4:30 - 5:30')])),
                ('assign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_classroom_app.class_courses')),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('usn', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('phoneno', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('DOB', models.DateField()),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_classroom_app.classroom')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='prof',
            fields=[
                ('prof_name', models.CharField(max_length=50)),
                ('desig', models.CharField(max_length=50)),
                ('prof_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_classroom_app.branch')),
            ],
        ),
        migrations.CreateModel(
            name='internals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ia1', models.IntegerField(default=0)),
                ('ia2', models.IntegerField(default=0)),
                ('ia3', models.IntegerField(default=0)),
                ('final_ia', models.FloatField(default=0.0)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_classroom_app.courses')),
                ('usn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_classroom_app.student')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='sem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_classroom_app.sem'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='sem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_classroom_app.sem'),
        ),
        migrations.AddField(
            model_name='class_courses',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_classroom_app.classroom'),
        ),
        migrations.AddField(
            model_name='class_courses',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_classroom_app.courses'),
        ),
        migrations.AddField(
            model_name='class_courses',
            name='prof_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_classroom_app.prof'),
        ),
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a1', models.IntegerField(default=0)),
                ('a2', models.IntegerField(default=0)),
                ('a3', models.IntegerField(default=0)),
                ('avg', models.FloatField(default=0.0)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_classroom_app.courses')),
                ('usn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_classroom_app.student')),
            ],
        ),
    ]
