# Generated by Django 2.2.14 on 2022-01-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_classroom_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internals',
            name='avg',
            field=models.FloatField(null=True),
        ),
    ]
