# Generated by Django 2.2.14 on 2022-01-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_classroom_app', '0002_auto_20220110_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='status',
        ),
        migrations.RemoveField(
            model_name='internals',
            name='a1',
        ),
        migrations.RemoveField(
            model_name='internals',
            name='a2',
        ),
        migrations.RemoveField(
            model_name='internals',
            name='a3',
        ),
        migrations.RemoveField(
            model_name='internals',
            name='avg',
        ),
        migrations.AddField(
            model_name='attendance',
            name='a1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='a2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='a3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='internals',
            name='final_ia',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='internals',
            name='ia1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='internals',
            name='ia2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='internals',
            name='ia3',
            field=models.IntegerField(default=0),
        ),
    ]
