# Generated by Django 4.0.1 on 2022-01-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_classroom_app', '0002_alter_time_table_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='usn',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
