# Generated by Django 4.0.1 on 2022-01-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_classroom_app', '0003_alter_student_usn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='usn',
            field=models.IntegerField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
